kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: agent-runtime
nodes:
  - role: control-plane
    image: ghcr.io/tom1299/agent-runtime/kindest/node-gvisor:v1.35.1
    extraMounts:
      - hostPath: /home/treuhl/git/github/agent-runtime
        containerPath: /workspace
